dynamic: True
resolution: 2
# Quad planning. These are not used by asoom, only for the quad mission
color: unity_urban_env.png
img_resolution: 2.66
image_origin_px_x: 529
image_origin_px_y: 235
quad_plan: unity_urban_env.plan
quad_plan_format: Sim
