- name: "color"
  format: ".png"
  type: "rgb"
- name: "elevation"
  format: ".png"
  type: "float"
- name: "semantics"
  format: ".png"
  type: "char"
- name: "semantics_viz"
  format: ".png"
  type: "rgb"
