dynamic: True
resolution: 2
# new bolton center
gps_origin_lat: 39.868680
gps_origin_long: -75.754088
# Quad planning. These are not used by asoom, only for the quad mission
color: nbc_color.png
img_resolution: 3.612
image_origin_px_x: 713
image_origin_px_y: 725
quad_plan: quad.plan
quad_plan_format: QGC
