dynamic: True
resolution: 2
# new bolton center
gps_origin_lat: 39.868680
gps_origin_long: -75.754088
# Quad planning. These are not used by asoom, only for the quad mission
# TODO: these are not correct
color: ../upenn/upenn_color.png
img_resolution: 2.438
image_origin_px_x: 1271
image_origin_px_y: 548
quad_plan: quad.plan
quad_plan_format: QGC
