dynamic: True
resolution: 2
# pennovation
gps_origin_lat: 39.9521998
gps_origin_long: -75.1935481
# Quad planning. These are not used by asoom, only for the quad mission
color: ../upenn/upenn_color.png
img_resolution: 2.438
image_origin_px_x: 1271
image_origin_px_y: 548
quad_plan: quad_plan.plan
quad_plan_format: QGC
